version: '3'
services:
  revolut-web:
    build:
        context: .
        dockerfile: Dockerfile.client
    ports:
    - "3000:80"
  revolut-api:
    build:
        context: .
        dockerfile: Dockerfile.server
    ports:
    - "5000:5000"

